name: Build Hugo Site

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build the site
      run: hugo

    - name: Upload public directory
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: public
